# Generated by Django 3.1.2 on 2020-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('air', 'air'), ('water', 'water'), ('food', 'food'), ('housing', 'housing'), ('health', 'health'), ('education', 'education'), ('transportation', 'transportation'), ('sexuality', 'sexuality')], max_length=25)),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('article_review', 'article_review'), ('book_review', 'book_review'), ('commentary', 'commentary')], default='article_review', max_length=25)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/upload/posts')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/upload/posts')),
                ('topics', models.ManyToManyField(to='posts.Topic')),
            ],
            options={
                'ordering': ['posted_date'],
            },
        ),
    ]
